language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: heroku_api_key
  on:
    branch: main
  app: rocky-crag-38133
  run:
    - rails db:migrate
    - restart
